In [11]:
import numpy as np
import pandas as pd
from ta import add_all_ta_features
from ta.utils import dropna

In [3]:
df = pd.read_csv("../data/sp500/trade_1_min_bars/AAPL.csv")
df.shape

(490961, 8)

In [6]:
df.dropna().shape

(490961, 8)

In [4]:
df.head()

,Date,Open,High,Low,Close,Volume,BarCount,Average
0,20211118 04:00:00,153.71,153.94,153.71,153.94,11,6,153.815
1,20211118 04:01:00,153.94,153.94,153.94,153.94,0,0,153.940
2,20211118 04:02:00,153.96,153.97,153.84,153.84,13,9,153.909
3,20211118 04:03:00,153.94,153.97,153.94,153.97,3,3,153.962
4,20211118 04:04:00,154.00,154.40,154.00,154.36,46,28,154.219

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490961 entries, 0 to 490960
Data columns (total 95 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Date                       490961 non-null  object
 1   Open                       490961 non-null  float64
 2   High                       490961 non-null  float64
 3   Low                        490961 non-null  float64
 4   Close                      490961 non-null  float64
 5   Volume                     490961 non-null  int64
 6   BarCount                   490961 non-null  int64
 7   Average                    490961 non-null  float64
 8   volume_adi                 490961 non-null  float64
 9   volume_obv                 490961 non-null  int64
 10  volume_cmf                 490961 non-null  float64
 11  volume_fi                  490961 non-null  float64
 12  volume_em                  490961 non-null  float64
 13  volume_sma_em              490961 non-null  float64
 14  volume_vpt                 490961 non-null  float64
 15  volume_vwap                490961 non-null  float64
 16  volume_mfi                 490961 non-null  float64
 17  volume_nvi                 490961 non-null  float64
 18  volatility_bbm             490961 non-null  float64
 19  volatility_bbh             490961 non-null  float64
 20  volatility_bbl             490961 non-null  float64
 21  volatility_bbw             490961 non-null  float64
 22  volatility_bbp             490961 non-null  float64
 23  volatility_bbhi            490961 non-null  float64
 24  volatility_bbli            490961 non-null  float64
 25  volatility_kcc             490961 non-null  float64
 26  volatility_kch             490961 non-null  float64
 27  volatility_kcl             490961 non-null  float64
 28  volatility_kcw             490961 non-null  float64
 29  volatility_kcp             490961 non-null  float64
 30  volatility_kchi            490961 non-null  float64
 31  volatility_kcli            490961 non-null  float64
 32  volatility_dcl             490961 non-null  float64
 33  volatility_dch             490961 non-null  float64
 34  volatility_dcm             490961 non-null  float64
 35  volatility_dcw             490961 non-null  float64
 36  volatility_dcp             490961 non-null  float64
 37  volatility_atr             490961 non-null  float64
 38  volatility_ui              490961 non-null  float64
 39  trend_macd                 490961 non-null  float64
 40  trend_macd_signal          490961 non-null  float64
 41  trend_macd_diff            490961 non-null  float64
 42  trend_sma_fast             490961 non-null  float64
 43  trend_sma_slow             490961 non-null  float64
 44  trend_ema_fast             490961 non-null  float64
 45  trend_ema_slow             490961 non-null  float64
 46  trend_vortex_ind_pos       490961 non-null  float64
 47  trend_vortex_ind_neg       490961 non-null  float64
 48  trend_vortex_ind_diff      490961 non-null  float64
 49  trend_trix                 490961 non-null  float64
 50  trend_mass_index           490961 non-null  float64
 51  trend_dpo                  490961 non-null  float64
 52  trend_kst                  490961 non-null  float64
 53  trend_kst_sig              490961 non-null  float64
 54  trend_kst_diff             490961 non-null  float64
 55  trend_ichimoku_conv        490961 non-null  float64
 56  trend_ichimoku_base        490961 non-null  float64
 57  trend_ichimoku_a           490961 non-null  float64
 58  trend_ichimoku_b           490961 non-null  float64
 59  trend_stc                  490961 non-null  float64
 60  trend_adx                  490961 non-null  float64
 61  trend_adx_pos              490961 non-null  float64
 62  trend_adx_neg              490961 non-null  float64
 63  trend_cci                  490961 non-null  float64
 64  trend_visual_ichimoku_a    490961 non-null  float64
 65  trend_visual_ichimoku_b    490961 non-null  float64
 66  trend_aroon_up             490961 non-null  float64
 67  trend_aroon_down           490961 non-null  float64
 68  trend_aroon_ind            490961 non-null  float64
 69  trend_psar_up              490961 non-null  float64
 70  trend_psar_down            490961 non-null  float64
 71  trend_psar_up_indicator    490961 non-null  float64
 72  trend_psar_down_indicator  490961 non-null  float64
 73  momentum_rsi               490961 non-null  float64
 74  momentum_stoch_rsi         490961 non-null  float64
 75  momentum_stoch_rsi_k       490961 non-null  float64
 76  momentum_stoch_rsi_d       490961 non-null  float64
 77  momentum_tsi               490961 non-null  float64
 78  momentum_uo                490961 non-null  float64
 79  momentum_stoch             490961 non-null  float64
 80  momentum_stoch_signal      490961 non-null  float64
 81  momentum_wr                490961 non-null  float64
 82  momentum_ao                490961 non-null  float64
 83  momentum_roc               490961 non-null  float64
 84  momentum_ppo               490961 non-null  float64
 85  momentum_ppo_signal        490961 non-null  float64
 86  momentum_ppo_hist          490961 non-null  float64
 87  momentum_pvo               490961 non-null  float64
 88  momentum_pvo_signal        490961 non-null  float64
 89  momentum_pvo_hist          490961 non-null  float64
 90  momentum_kama              490961 non-null  float64
 91  others_dr                  490961 non-null  float64
 92  others_dlr                 490961 non-null  float64
 93  others_cr                  490961 non-null  float64
 94  log_return                 490960 non-null  float64
dtypes: float64(91), int64(3), object(1)
memory usage: 355.8+ MB

In [7]:
df = add_all_ta_features(df, open="Open", high="High", low="Low", close="Close", volume="Volume", fillna=True)

C:\Users\yurit\anaconda3\envs\ib\lib\site-packages\ta\trend.py:780: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
C:\Users\yurit\anaconda3\envs\ib\lib\site-packages\ta\trend.py:785: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)

In [8]:
df.head()

,Date,Open,High,Low,Close,Volume,BarCount,Average,volume_adi,volume_obv,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
0,20211118 04:00:00,153.71,153.94,153.71,153.94,11,6,153.815,11.0,11,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,153.940000,-0.682800,0.000000,0.000000
1,20211118 04:01:00,153.94,153.94,153.94,153.94,0,0,153.940,11.0,11,...,0.000000,0.000000,0.000000,-8.615385,-1.723077,-6.892308,153.940000,0.000000,0.000000,0.000000
2,20211118 04:02:00,153.96,153.97,153.84,153.84,13,9,153.909,-2.0,-2,...,-0.005182,-0.001036,-0.004146,-4.983315,-2.375125,-2.608191,153.896670,-0.064960,-0.064981,-0.064960
3,20211118 04:03:00,153.94,153.97,153.94,153.97,3,3,153.962,1.0,1,...,-0.002446,-0.001318,-0.001128,-10.441547,-3.988409,-6.453138,153.927470,0.084503,0.084468,0.019488
4,20211118 04:04:00,154.00,154.40,154.00,154.36,46,28,154.219,37.8,47,...,0.019931,0.002932,0.017000,16.082366,0.025746,16.056620,154.093753,0.253296,0.252976,0.272834

In [20]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Open,490961.0,1.549986e+02,13.164766,124.200000,145.100000,1.544400e+02,165.460000,183.380000
High,490961.0,1.550501e+02,13.164338,124.250000,145.150000,1.544900e+02,165.500000,183.380000
Low,490961.0,1.549462e+02,13.164960,124.170000,145.040000,1.543900e+02,165.410000,183.360000
Close,490961.0,1.549983e+02,13.164791,124.200000,145.100000,1.544400e+02,165.460000,183.360000
Volume,490961.0,7.557842e+02,3381.044079,0.000000,3.000000,4.200000e+01,1046.000000,494185.000000
...,...,...,...,...,...,...,...,...
momentum_kama,490961.0,1.549977e+02,13.163688,124.372400,145.109375,1.544358e+02,165.454214,183.344105
others_dr,490961.0,5.163512e-05,0.081537,-9.392538,-0.023028,0.000000e+00,0.023115,11.536680
others_dlr,490961.0,1.972068e-05,0.081666,-9.863361,-0.023030,0.000000e+00,0.023112,10.918332
others_cr,490961.0,6.874939e-01,8.551897,-19.319215,-5.742497,3.248019e-01,7.483435,19.111342
log_return,490960.0,-2.045080e-07,0.000762,-0.109160,-0.000207,-6.478362e-09,0.000204,0.097270

In [19]:
df["log_return"] = np.log(df["Average"].shift(1)/(df["Average"] + 1e-6))

In [9]:
df.shape

(490961, 94)

In [10]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'BarCount', 'Average',
       'volume_adi', 'volume_obv', 'volume_cmf', 'volume_fi', 'volume_em',
       'volume_sma_em', 'volume_vpt', 'volume_vwap', 'volume_mfi',
       'volume_nvi', 'volatility_bbm', 'volatility_bbh', 'volatility_bbl',
       'volatility_bbw', 'volatility_bbp', 'volatility_bbhi',
       'volatility_bbli', 'volatility_kcc', 'volatility_kch', 'volatility_kcl',
       'volatility_kcw', 'volatility_kcp', 'volatility_kchi',
       'volatility_kcli', 'volatility_dcl', 'volatility_dch', 'volatility_dcm',
       'volatility_dcw', 'volatility_dcp', 'volatility_atr', 'volatility_ui',
       'trend_macd', 'trend_macd_signal', 'trend_macd_diff', 'trend_sma_fast',
       'trend_sma_slow', 'trend_ema_fast', 'trend_ema_slow',
       'trend_vortex_ind_pos', 'trend_vortex_ind_neg', 'trend_vortex_ind_diff',
       'trend_trix', 'trend_mass_index', 'trend_dpo', 'trend_kst',
       'trend_kst_sig', 'trend_kst_diff', 'trend_ichimoku_conv',
       'trend_ichimoku_base', 'trend_ichimoku_a', 'trend_ichimoku_b',
       'trend_stc', 'trend_adx', 'trend_adx_pos', 'trend_adx_neg', 'trend_cci',
       'trend_visual_ichimoku_a', 'trend_visual_ichimoku_b', 'trend_aroon_up',
       'trend_aroon_down', 'trend_aroon_ind', 'trend_psar_up',
       'trend_psar_down', 'trend_psar_up_indicator',
       'trend_psar_down_indicator', 'momentum_rsi', 'momentum_stoch_rsi',
       'momentum_stoch_rsi_k', 'momentum_stoch_rsi_d', 'momentum_tsi',
       'momentum_uo', 'momentum_stoch', 'momentum_stoch_signal', 'momentum_wr',
       'momentum_ao', 'momentum_roc', 'momentum_ppo', 'momentum_ppo_signal',
       'momentum_ppo_hist', 'momentum_pvo', 'momentum_pvo_signal',
       'momentum_pvo_hist', 'momentum_kama', 'others_dr', 'others_dlr',
       'others_cr'],
      dtype='object')

In [ ]:
from ta.momentum import